package br.com.sgv.view;

import br.com.sgv.enumerator.CalcTypeEnum;
import br.com.sgv.model.Sale;
import br.com.sgv.service.LogService;
import br.com.sgv.service.SaleService;
import br.com.sgv.shared.FormatMoney;
import br.com.sgv.shared.ResponseModel;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.time.Instant;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * @author Anderson Junior Rodrigues
 */

public class ListSaleDay extends javax.swing.JDialog {

    private LogService logService = null;
    private DefaultTableModel table = null;
    private List<Sale> listSales = null;
    private double totalValue;
    
    public ListSaleDay(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public void initScreen() {
        this.logService = new LogService(Sale.class.getName(), "ListSaleDay");
        
        this.initDatePicker();
        this.getSalesByDay(true);
        
        this.setSize(600, 500);
        this.setLocationRelativeTo(null);
        this.pack();
        this.setVisible(true);
    }
    
    private void initDatePicker() {
        dpkSearchDay.setFormats(new String[] {"dd/MM/yyyy"});
        dpkSearchDay.setDate(Date.from(Instant.now()));
        dpkSearchDay.setLinkDate(System.currentTimeMillis(), "Hoje é {0}");
    }
    
    private void getSalesByDay(boolean isInit) {
        try {
            if (verifyFields()) {
                this.logService.logMessage("inicio de busca de vendas por dia", "getSalesByDay");
                Date dateSearch = dpkSearchDay.getDate();
                ResponseModel<List<Sale>> response = new SaleService().getSalesByDay(dateSearch);
                this.listSales = response.getModel();

                this.setSaleTable(isInit);
            }
        } catch(Exception ex){
            this.logService.logMessage(ex.toString(), "getSalesByDay");
            JOptionPane.showMessageDialog(null, "Falha ao buscar os dados.");
        }
    }
    
    private void setSaleTable(boolean isInit) {
        this.table = (DefaultTableModel)tableSale.getModel();
        this.table.setRowCount(0);
        this.totalValue = 0d;
        this.logService.logMessage("atualizando tabela de vendas", "setSaleTable");
        
        this.listSales.stream().forEach(sale -> {
            String amount;
            
            if (sale.getProduct().getMeasureType().getCalcType().getId() == CalcTypeEnum.UNITY.value) {
                amount = String.valueOf((int)sale.getAmount());
            } else {
                amount = FormatMoney.verifyDecimal(String.valueOf(sale.getAmount()), CalcTypeEnum.WEIGHT.value);
            }
            
            this.table.addRow(new Object[] {
                sale.getProduct().getProductName(),
                new SimpleDateFormat("HH:mm:ss").format(sale.getSaleDate()),
                "R$ " + new DecimalFormat("#0.00").format(sale.getProduct().getProductValue()),
                amount,
                "R$ " + new DecimalFormat("#0.00").format(sale.getSaleTotal())
            });
            
            this.totalValue += sale.getSaleTotal();
        });
        
        if (this.listSales == null || this.listSales.size() <= 0 && !isInit) {
            this.logService.logMessage("nenhuma venda encontrada", "setSaleTable");
            JOptionPane.showMessageDialog(null, "Nenhuma venda encontrada.");
        }
        
        this.logService.logMessage("calculando total de vendas", "setSaleTable");
        String totalValueString = new DecimalFormat("#0.00").format(this.totalValue);
        lblTotalSale.setText("R$ " + totalValueString);
    }
    
    private boolean verifyFields() {
        boolean isVerify = true;
        String message = "";
        
        if (dpkSearchDay.getDate().toString().isEmpty()) {
            message += "Data obrigatória!\n";
        }
        
        if (dpkSearchDay.getDate().after(Date.from(Instant.now()))) {
            message += "Data informada não pode ser maior que a data atual.\n";
        }
        
        if (!message.isEmpty()) {
            JOptionPane.showMessageDialog(null, message);
            isVerify = false;
        }
        
        return isVerify;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dpkSearchDay = new org.jdesktop.swingx.JXDatePicker();
        lblSearchDay = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        btnSearchDay = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableSale = new javax.swing.JTable();
        lblTotal = new javax.swing.JLabel();
        lblTotalSale = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sistema de Gerenciamento de Vendas");

        lblSearchDay.setText("Dia da Consulta..:");

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTitle.setText("Consulta de Venda por Dia");

        btnSearchDay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sgv/images/png/Find.png"))); // NOI18N
        btnSearchDay.setText("Pesquisar");
        btnSearchDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchDayActionPerformed(evt);
            }
        });

        tableSale.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Produto", "Hora Venda", "Valor Produto", "Quantidade", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableSale);
        if (tableSale.getColumnModel().getColumnCount() > 0) {
            tableSale.getColumnModel().getColumn(0).setResizable(false);
            tableSale.getColumnModel().getColumn(0).setPreferredWidth(220);
            tableSale.getColumnModel().getColumn(1).setResizable(false);
            tableSale.getColumnModel().getColumn(1).setPreferredWidth(70);
            tableSale.getColumnModel().getColumn(2).setResizable(false);
            tableSale.getColumnModel().getColumn(2).setPreferredWidth(70);
            tableSale.getColumnModel().getColumn(3).setResizable(false);
            tableSale.getColumnModel().getColumn(3).setPreferredWidth(70);
            tableSale.getColumnModel().getColumn(4).setResizable(false);
            tableSale.getColumnModel().getColumn(4).setPreferredWidth(70);
        }

        lblTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTotal.setText("Total Venda..:");

        lblTotalSale.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTotalSale.setText("R$ 0,00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSearchDay)
                                    .addComponent(dpkSearchDay, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSearchDay))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(207, 207, 207)
                                .addComponent(lblTitle)))
                        .addGap(0, 200, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblTotal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTotalSale)
                .addGap(95, 95, 95))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblTitle)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSearchDay)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dpkSearchDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnSearchDay))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalSale)
                    .addComponent(lblTotal))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchDayActionPerformed
        this.getSalesByDay(false);
    }//GEN-LAST:event_btnSearchDayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListSaleDay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListSaleDay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListSaleDay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListSaleDay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ListSaleDay dialog = new ListSaleDay(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearchDay;
    private org.jdesktop.swingx.JXDatePicker dpkSearchDay;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSearchDay;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTotalSale;
    private javax.swing.JTable tableSale;
    // End of variables declaration//GEN-END:variables
}
