package br.com.sgv.view;

import br.com.sgv.model.MeasureType;
import br.com.sgv.service.LogService;
import br.com.sgv.service.MeasureTypeService;
import br.com.sgv.shared.ResponseModel;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * @author Anderson Junior Rodrigues
 */
public class ListMeasure extends javax.swing.JDialog {

    private RegisterMeasure registerMeasure = null;
    private ResponseModel<List<MeasureType>> listResponse = null;
    private LogService logService = null;
    
    public ListMeasure(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public void initScreen() {
        this.logService = new LogService(LogService.class.getName(), "ListMeasure");
        this.getMeasureType();
        
        this.setSize(600, 400);
        this.setLocationRelativeTo(this);
        this.pack();
        this.setVisible(true);
    }
    
    private void getMeasureType() {
        try {
            this.logService.logMessage("requesição de busca de volumes", "getMeasureType");
            this.listResponse = new MeasureTypeService().getMeasureType();
            List<MeasureType> listMeasureType = this.listResponse.getModel();

            if (listMeasureType != null && listMeasureType.size() > 0) {
                DefaultTableModel table = (DefaultTableModel)tblMeasure.getModel();

                listMeasureType.stream().forEach(measure -> {
                    table.addRow(new Object[] {
                        measure.getMeasureType(), 
                        measure.getInitials(), 
                        measure.getCalcType().getCalcType()
                    });
                });            
            }
        } catch (Exception ex){
            this.logService.logMessage(ex.toString(), "getMeasureType");
            JOptionPane.showMessageDialog(null, "Falha ao buscar os dados.");
        }
    }
    
    private void AddMeasure() {
        this.closeScreen();
        
        this.registerMeasure = new RegisterMeasure(null, true);
        this.registerMeasure.initScreen();
    }
    
    private void closeScreen() {
        this.listResponse = null;
        this.logService = null;
        
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMeasure = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMeasure = new javax.swing.JTable();
        btnClose = new javax.swing.JButton();
        btnNew = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sistema de Gerenciamento de Vendas");

        lblMeasure.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblMeasure.setText("Lista de Volumes Cadastrados");

        tblMeasure.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Unidade de Medida", "Sigla", "Tipo de Calculo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblMeasure);
        if (tblMeasure.getColumnModel().getColumnCount() > 0) {
            tblMeasure.getColumnModel().getColumn(0).setMinWidth(300);
            tblMeasure.getColumnModel().getColumn(0).setPreferredWidth(300);
            tblMeasure.getColumnModel().getColumn(0).setMaxWidth(300);
            tblMeasure.getColumnModel().getColumn(1).setMinWidth(100);
            tblMeasure.getColumnModel().getColumn(1).setPreferredWidth(100);
            tblMeasure.getColumnModel().getColumn(1).setMaxWidth(100);
            tblMeasure.getColumnModel().getColumn(2).setMinWidth(200);
            tblMeasure.getColumnModel().getColumn(2).setPreferredWidth(200);
            tblMeasure.getColumnModel().getColumn(2).setMaxWidth(200);
        }

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sgv/images/png/Erase.png"))); // NOI18N
        btnClose.setText("Fechar");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        btnNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sgv/images/png/Add.png"))); // NOI18N
        btnNew.setText("Adicionar");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(lblMeasure)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnNew)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClose)
                .addGap(202, 202, 202))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblMeasure)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClose)
                    .addComponent(btnNew))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.closeScreen();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        this.AddMeasure();
    }//GEN-LAST:event_btnNewActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListMeasure.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ListMeasure dialog = new ListMeasure(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnNew;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMeasure;
    private javax.swing.JTable tblMeasure;
    // End of variables declaration//GEN-END:variables
}
